services:
  app:
    build:
      context: ./housing-api
    container_name: housing-api-app
    ports:
      - "8000:8000"
    env_file:
      - ./housing-api/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: housing-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bSeEHAPtQHrzhmLjTPppeagYaLkDwasS
      POSTGRES_DB: railway
    restart: always
